// Action Types

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const GET_CART_PRODUCTS_LOCALSTORAGE_START =
  "GET_CART_PRODUCTS_LOCALSTORAGE_START";
export const GET_CART_PRODUCTS_LOCALSTORAGE_SUCCESS =
  "GET_CART_PRODUCTS_LOCALSTORAGE_SUCCESS";
