// Action types
import { createConstant } from "./utils";

export const INITIALIZE_APP = createConstant("INITIALIZE_APP");
export const SIGN_IN_ENTER_PHONE = createConstant("USER_SIGN_IN_ENTER_PHONE");
export const SIGN_IN_ENTER_OTP = createConstant("USER_SIGN_IN_ENTER_OTP");
export const USER_DATA_CHANGE = createConstant("USER_DATA_CHANGE");
export const LOG_OUT = createConstant("USER_LOG_OUT");

export const MODAL_CHANGE = "USER_MODAL_CHANGE";
export const LANGUAGE_CHANGE = "USER_LANGUAGE_CHANGE";

export const SIGN_UP = createConstant("USER_SIGN_UP");
export const LOG_IN = createConstant("USER_LOG_IN");

export const ADD_TO_USER_WISHLIST = "ADD_TO_USER_WISHLIST";
export const REMOVE_FROM_USER_WISHLIST = "REMOVE_FROM_USER_WISHLIST";
export const GET_USERS_WISHLIST_START = "GET_USERS_WISHLIST_START";
export const GET_USERS_WISHLIST_SUCCESS = "GET_USERS_WISHLIST_SUCCESS";
export const GET_USER_ORDER_HISTORY_AND_ADDRESSES_AND_START =
  "GET_USER_ORDER_HISTORY_AND_ADDRESSES_AND_START";
export const GET_USER_ORDER_HISTORY_SUCCESS = "GET_USER_ORDER_HISTORY_SUCCESS";
export const GET_USER_ADDRESSES_SUCCESS = "GET_USER_ADDRESSES_SUCCESS";
export const GET_PICK_UP_POINTS_SUCCESS = "GET_PICK_UP_POINTS_SUCCESS";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const SET_DELIVERY_INFO = "SET_DELIVERY_INFO";
export const CHECKOUT_ORDER_START = "CHECKOUT_ORDER_START";
export const ADD_USER_ADDRESS_START = "ADD_USER_ADDRESS_START";
export const REMOVE_USER_ADDRESS_START = "REMOVE_USER_ADDRESS_START";
export const GET_ALL_LANGUAGES_SUCCESS = "GET_ALL_LANGUAGES_SUCCESS";
