// const colors = require('tailwindcss/colors')

module.exports = {
  purge: {
    enabled: true,
    content: [
      "./pages/**/*.js",
      "./pages/**/*.jsx",
      "./styles/**/*.css",
      "./src/**/*js",
      "./src/**/*jsx",
    ],
  },
  darkMode: false,
  theme: {
    container: {
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
    },
    boxShadow: {
      catalog: "0 2px 3px 0 rgba(0,0,0,.2)",
      all: "0 0px 2px 1px rgba(0,0,0,.2)",
      icon: "",
      errorPanel: "0 19px 38px rgba(0,0,0, 0.3), 0 15px 12px rgba(0,0,0,0.22)",
    },
    extend: {},
    backgroundColor: (theme) => ({
      ...theme("colors"),
      // customPink: "#f91155",
      customBlue1: "#005bff",
      customBlue2: "#004ed6",
      customDarkBlue: "#001a34",
      customDarkBlue2: "#012250",
      customOrange: "#ff8400",
      customViolet: "#7d36aa",
      customYellow: "#fae670",
      customGreen: "#3ac267",
      customGrey: "#f2f3f5",
      customLightGray: "#f2f3f5",
      customLightGrayHover: "#eaedef",
      customGreyText: "#808d9a",
      customLightBlack: "#4d5f71",
      searchFilterItBg: "#E5EFFF",
      bg-modalBg: "#f8f8f8",
      customWhite: "#ff6b6b",
      customRed: "#f03",
      customGr: "#99BDFF",
      customGreyBottom: "#d6dbe0",
      customSwitcher: "#C2EECF",
    }),
    textColor: (theme) => ({
      ...theme("colors"),
      customPink: "#f91155",
      customBlue1: "#005bff",
      customBlue2: "#004ed6",
      customDarkBlue: "#001a34",
      customDarkBlue2: "#012250",
      customOrange: "#ff8400",
      customViolet: "#7d36aa",
      customYellow: "#fae670",
      customGreen: "#3ac267",
      customGrey: "#f2f3f5",
      allbestcardBalck: "#001a34",
      customGreyText: "#808d9a",
      customLightBlack: "#4d5f71",
      searchFilterItBg: "#E5EFFF",
      bg-modalBg: "#f8f8f8",
      customWhite: "#edf2f4",
      customGr: "#99BDFF",
      customGreyBottom: "#d6dbe0",
    }),
    borderColor: (theme) => ({
      ...theme("colors"),
      customYellow: "#fae670",
      customGrey: "#f2f3f5",
      customBlue1: "#005bff",
      customBlue2: "#004ed6",
      customDarkBlue: "#001a34",
      customDarkBlue2: "#012250",
      customGreyBottom: "#d6dbe0",
      customGreyText: "#808d9a",
    }),
  },

  variants: {
    extend: {},
  },
  plugins: ["tailwindcss", "postcss-flexbugs-fixes"],
};
