// Action Types

export const SET_ACTION_STATUS = "SET_ACTION_STATUS";
export const GET_ALL_CURRENCIES_START = "GET_ALL_CURRENCIES_START";
export const GET_ALL_CURRENCIES_SUCCESS = "GET_ALL_CURRENCIES_SUCCESS";
export const SET_SELECTED_CURRENCY = "SET_SELECTED_CURRENCY";
