// Action Types

export const GET_HOME_PAGE_START = "GET_HOME_PAGE_START";
export const SET_LOADING = "SET_LOADING";
export const GET_HOME_PAGE_SUCCESS = "GET_HOME_PAGE_SUCCESS";
export const GET_PAGE_HTML_START = "GET_PAGE_HTML_START";
export const GET_PAGE_HTML_SUCCESS = "GET_PAGE_HTML_SUCCESS";
