// Action Types
import { createConstant } from "../user/utils";

export const GET_ALL_CATEGORIES_START = "GET_ALL_CATEGORIES_START";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_PRODUCT_INFO_START = "GET_PRODUCT_INFO_START";
export const GET_PRODUCT_INFO_SUCCESS = "GET_PRODUCT_INFO_SUCCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const SET_SELECTED_SUB_CATEGORY_ID = "SET_SELECTED_SUB_CATEGORY_ID";
export const UPDATE_FILTER_QUERIES_FOR_CATEGORY =
  "UPDATE_FILTER_QUERIES_FOR_CATEGORY";
export const SET_SELECTED_SUB_CATEGORY_SUCCESS =
  "SET_SELECTED_SUB_CATEGORY_SUCCESS";
export const GET_SELECTED_CATEGORY_SUB_CATEGORIES_START =
  "GET_SELECTED_CATEGORY_SUB_CATEGORIES_START";
export const GET_SELECTED_CATEGORY_SUB_CATEGORIES_SUCCESS =
  "GET_SELECTED_CATEGORY_SUB_CATEGORIES_SUCCESS";
export const GET_CATEGORY_PRODUCTS_START = "GET_CATEGORY_PRODUCTS_START";
export const GET_CATEGORY_PRODUCTS_SUCCESS = "GET_CATEGORY_PRODUCTS_SUCCESS";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCH_TEXT_RESULTS = "SET_SEARCH_TEXT_RESULTS";
export const GET_RELATED_PRODUCTS_OF_PRODUCT_SUCCESS =
  "GET_RELATED_PRODUCTS_OF_PRODUCT_SUCCESS";
export const GET_FEATURED_CATEGORIES_SUCCESS =
  "GET_FEATURED_CATEGORIES_SUCCESS";
export const SET_SELECTED_PRODUCT_VARIANT = "SET_SELECTED_PRODUCT_VARIANT";
export const GET_SELLER_DETAILS_START = "GET_SELLER_DETAILS_START";
export const GET_SELLER_DETAILS_SUCCESS = "GET_SELLER_DETAILS_SUCCESS";
export const GET_ALL_MARKETS_START = "GET_ALL_MARKETS_START";
export const GET_ALL_MARKETS_SUCCESS = "GET_ALL_MARKETS_SUCCESS";
export const GET_SELLER_PRODUCTS = createConstant("GET_SELLER_PRODUCTS");

export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_START = "GET_BRANDS_START";

export const WRITE_COMMENT_TO_PRODUCT_START = "WRITE_COMMENT_TO_PRODUCT_START";
export const ADD_PRODUCT_FOR_COMPARING = "ADD_PRODUCT_FOR_COMPARING";
export const GET_PRODUCTS_FOR_COMPARING_SUCCESS =
  "GET_PRODUCTS_FOR_COMPARING_SUCCESS";
